version: "3.9"

services:
  backend:
    build: ./backend
    environment:
      FLASK_APP: run.py
      FLASK_ENV: production
      FLASK_DB_TYPE: postgres
      FLASK_DB_USER: postgres
      FLASK_DB_NAME: postgres
      FLASK_DB_PASSWORD: secretpass
      FLASK_DB_HOST: db
      FLASK_DB_PORT: 5432
    expose:
      - "5000"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
